### PR TITLE
Upgrade Flutter version to 1.9.1+hotfix.6

### PR DESCRIPTION
**Pull request by Matsue**
This Pull Request upgrades Flutter version to latest stable.

* https://flutter.dev/docs/development/tools/sdk/releases
* Changelogs
	* https://github.com/flutter/flutter/releases/tag/v1.9.1%2Bhotfix.3
	* https://github.com/flutter/flutter/releases/tag/v1.9.1%2Bhotfix.4
	* https://github.com/flutter/flutter/releases/tag/v1.9.1%2Bhotfix.5
	* https://github.com/flutter/flutter/releases/tag/v1.9.1%2Bhotfix.6

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added

### CODE REVIEW

**Comment by Matsue** [comment]
@mikloslorinczi 
Thanks for your review, I will add an entry to the CHANGELOG.

**Comment by Matsue** [comment]
I added an entry to the CHANGELOG, please check it.

**Comment by Matsue** [comment]
@mikloslorinczi
Please check the updates of this PR. This PR status is "change requested", so your review is necessary.

**Comment by Matsue** [comment]
@mikloslorinczi 

I updated the revID on `bitrise_profile`, please check it.

**Comment by viktorbenei** [comment]
@mikloslorinczi the revID addition to CHANGELOG seems to be missing from the PR template - please add it to it!

**Pull request merged**
