### PR TITLE
Speed up .net core builds on first launch

### PR DESCRIPTION
**Pull request by stefandevo**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [x] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added

### CODE REVIEW

**Comment by stefandevo** [comment]
Question: are these applied to all Xamarin stacks? (beta, alpha, stable). Furthermore, one of my previous PRs adds .net core to the box, same question here -> will these be applied to all Xam stacks?

**Comment by viktorbenei** [comment]
> Question: are these applied to all Xamarin stacks? (beta, alpha, stable).

Yes, on every new Xamarin stack. So it won't be applied on the LTS one, but will be on the non LTS ones (and if we'd update the LTS one in the future, it'll get it too at that point).

> Furthermore, one of my previous PRs adds .net core to the box, same question here -> will these be applied to all Xam stacks?

Same answer ;)

Basically the Xamarin stacks are built on top of the latest Xcode stable stack (Xcode 8.3.2 this week). The things installed in the Xcode "layer" are not updated, but the xamarin specific things are updated every week.

**Comment by stefandevo** [comment]
Ok. Clear! Thanks.

**Comment by viktorbenei** [comment]
More info: https://discuss.bitrise.io/t/how-are-the-bitrise-io-stacks-updated-and-with-what-frequency/281

**Pull request merged**
