### PR TITLE
adding docker to image

### PR DESCRIPTION
**Pull request by jmo-gs**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [X] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [X] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added

### Comments
We're exited to use your product! This change is fundamental to how we work (a mono repo with docker and iOS builds).

### Related Discussion
https://discuss.bitrise.io/t/how-to-use-your-own-docker-image-for-your-builds/69
https://github.com/bitrise-io/osx-box-bootstrap/issues/40

### CODE REVIEW

**Comment by viktorbenei** [comment]
Hmm.. Actually, testing this, a simple `brew cask install docker` doesn't seem to be enough.

```
brew cask install docker
...
docker version
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise092632730/step_src/._script_cont: line 4: docker: command not found
...
```

Still checking

**Comment by viktorbenei** [comment]
Seems a symlink is missing when docker for mac is installed through brew cask:

https://stackoverflow.com/a/40523608/974381

**Comment by viktorbenei** [comment]
Decided to revert this PR for now, as it does not work without the symlinks.

Symlinks applied by Docker for Mac when installed through the GUI installer:

```
ls -alh /usr/local/bin/ | grep docker
lrwxr-xr-x    1 viktorbenei  staff    71B May 31 10:53 docker -> /Users/viktorbenei/Library/Group Containers/group.com.docker/bin/docker
lrwxr-xr-x    1 viktorbenei  staff    79B May 31 10:53 docker-compose -> /Users/viktorbenei/Library/Group Containers/group.com.docker/bin/docker-compose
lrwxr-xr-x    1 viktorbenei  staff    94B May 31 10:53 docker-credential-osxkeychain -> /Users/viktorbenei/Library/Group Containers/group.com.docker/bin/docker-credential-osxkeychain
lrwxr-xr-x    1 viktorbenei  staff    79B May 31 10:53 docker-machine -> /Users/viktorbenei/Library/Group Containers/group.com.docker/bin/docker-machine
lrwxr-xr-x    1 viktorbenei  staff    71B May 31 10:53 notary -> /Users/viktorbenei/Library/Group Containers/group.com.docker/bin/notary
```

**Comment by viktorbenei** [comment]
Actually there's one more redirection, which symlinks to `/Applications/Docker.app/Contents/Resources/bin/`, so e.g. `/usr/local/bin/docker` is actually symlinked to `/Applications/Docker.app/Contents/Resources/bin/docker` just through an intermediate symlink

```
ls -alh '/Users/viktorbenei/Library/Group Containers/group.com.docker/bin'
total 48
drwxr-xr-x  8 viktorbenei  staff   272B May 31 10:53 .
drwx------  5 viktorbenei  staff   170B Mar  4 21:53 ..
lrwxr-xr-x  1 viktorbenei  staff    54B May 31 10:53 docker -> /Applications/Docker.app/Contents/Resources/bin/docker
lrwxr-xr-x  1 viktorbenei  staff    62B May 31 10:53 docker-compose -> /Applications/Docker.app/Contents/Resources/bin/docker-compose
lrwxr-xr-x  1 viktorbenei  staff    81B May 31 10:53 docker-credential-osxkeychain -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-osxkeychain.bin
lrwxr-xr-x  1 viktorbenei  staff    63B May 31 10:53 docker-diagnose -> /Applications/Docker.app/Contents/Resources/bin/docker-diagnose
lrwxr-xr-x  1 viktorbenei  staff    62B May 31 10:53 docker-machine -> /Applications/Docker.app/Contents/Resources/bin/docker-machine
lrwxr-xr-x  1 viktorbenei  staff    54B May 31 10:53 notary -> /Applications/Docker.app/Contents/Resources/bin/notary
```

**Comment by viktorbenei** [comment]
@jmo-gs I'd suggest you to just write a Script and run it on bitrise.io (e.g. create a completely empty project on bitrise.io, with a single Script step in its workflow - no need for Git Clone either)

If that works and you can get `docker version` after that then just submit it here and we'll transform that into a PR

Note for ourselves: we should connect a PR check in this repo, even if just a basic one

**Comment by viktorbenei** [comment]
For reference this is the `bitrise.yml` I tested with:

```
format_version: 1.1.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
trigger_map:
- push_branch: '*'
  workflow: install-docker
workflows:
  install-docker:
    steps:
    - script@1.1.3:
        title: brew cask install docker
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            brew cask install docker
    - script@1.1.3:
        title: docker version
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            docker version
    - script@1.1.3:
        title: docker run hello-world
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            docker run hello-world

```

**Comment by viktorbenei** [comment]
Implementation note: so far it seems that simply iterating through the content of `/Applications/Docker.app/Contents/Resources/bin` and symlinking all the binaries from there into `/usr/local/bin` should work, but didn't have the time to write a proper script for this yet

**Comment by jmo-gs** [comment]
Thanks for running this! I've been investigating getting this working and have found the following:
1) The symlinking works
2) In the usual setup, Docker.app must run to start the background docker service. It has UI elements that require clicking to actually get setup. I can't figure out how to avoid this but still use the Docker.app.
3) One way avoid the UI elements (i.e., become headless) is to use `docker-machine` + virtualbox
4) If using `docker-machine` + virtualbox, there are cert errors:
```
Running pre-create checks...
(default) Image cache directory does not exist, creating it at /Users/vagrant/.docker/machine/cache...
(default) No default Boot2Docker ISO found locally, downloading the latest release...
Error with pre-create check: "Get https://api.github.com/repos/boot2docker/boot2docker/releases/latest: x509: certificate signed by unknown authority"
```
https://github.com/docker/machine/issues/3595 doesn't seem to help.

https://github.com/GyroscopeHQ/test-bitrise-docker/blob/master/bitrise.yml contains the changes that, once completely working, I can move into the playbook.

Working on 4 right now. Any thoughts on the certs? Are these images missing basic certs by chance?

**Comment by viktorbenei** [comment]
> The symlinking works

Sounds good! ;)

> In the usual setup, Docker.app must run to start the background docker service. It has UI elements that require clicking to actually get setup. I can't figure out how to avoid this but still use the Docker.app.

You should ask this from the brew guys / from this brew cask maintainer who sent in this formulae into brew; I don't have any experience with installing Docker.app through brew cask unfortunately.

> One way avoid the UI elements (i.e., become headless) is to use docker-machine + virtualbox

Indeed, but that's no longer the official solution (the only official one is right now the Docker.app as far as I know), and so we won't preinstall that as we only accept official solutions. That doesn't mean that you can't do it yourself with a Script step in the build for example, just that we won't have it in this provisioning repo due to long term maintenance concerns.

> Any thoughts on the certs? Are these images missing basic certs by chance?

There's nothing special here, these VMs are clean macOS installs, with Xcode.app installed on it and then this repository is auto performed on top of that. Nothing's customized or modified in macOS, no certs are removed or anything like that. Everything we do is listed in the README (https://github.com/bitrise-io/osx-box-bootstrap/blob/master/README.md) even the manual steps.

**Note:** from the original discussion it seems that `docker-toolbox` should work out-of-the-box. See: https://discuss.bitrise.io/t/how-to-use-your-own-docker-image-for-your-builds/69/9?u=viktorbenei

But as I explained it there, due to docker toolbox is no longer the officially sanctioned solution by Docker we don't really want to preinstall that (again, long term maintenance concerns) but you're free to use that if you like it.

If you have any questions just let us know!

**Comment by jmo-gs** [comment]
On Thu, Jun 1, 2017 at 5:39 AM, Viktor Benei <notifications@github.com>
wrote:

> The symlinking works
>
> Sounds good! ;)
>
> In the usual setup, Docker.app must run to start the background docker
> service. It has UI elements that require clicking to actually get setup. I
> can't figure out how to avoid this but still use the Docker.app.
>
> You should ask this from the brew guys / from this brew cask maintainer
> who sent in this formulae into brew; I don't have any experience with
> installing Docker.app through brew cask unfortunately.
>
My impression is that this is beyond the scope of brew cask. I am going to
submit a request to Docker.

> One way avoid the UI elements (i.e., become headless) is to use
> docker-machine + virtualbox
>
> Indeed, but that's no longer the official solution (the only official one
> is right now the Docker.app as far as I know), and so we won't preinstall
> that as we only accept official solutions. That doesn't mean that you can't
> do it yourself with a Script step in the build for example, just that we
> won't have it in this provisioning repo due to long term maintenance
> concerns.
>
My understanding from the below references is that it is indeed "official"
but for those that don't meet the requirements of the other apps (in this
case, a requirement is a UI). It does seem supported. Though, I understand
the decision.
https://docs.docker.com/docker-for-mac/docker-toolbox/
https://docs.docker.com/toolbox/overview/

> Any thoughts on the certs? Are these images missing basic certs by chance?
>
> There's nothing special here, these VMs are clean macOS installs, with
> Xcode.app installed on it and then this repository is auto performed on top
> of that. Nothing's customized or modified in macOS, no certs are removed or
> anything like that. Everything we do is listed in the README (
> https://github.com/bitrise-io/osx-box-bootstrap/blob/master/README.md)
> even the manual steps.
>
> *Note:* from the original discussion it seems that docker-toolbox should
> work out-of-the-box. See: https://discuss.bitrise.io/t/
> how-to-use-your-own-docker-image-for-your-builds/69/9?u=viktorbenei
>
> But as I explained it there, due to docker toolbox is no longer the
> officially sanctioned solution by Docker we don't really want to preinstall
> that (again, long term maintenance concerns) but you're free to use that if
> you like it.
>
We'll try that! Looks like it only adds about ~3min to the build time.


> If you have any questions just let us know!
>
Thanks so much, your responsiveness is amazing! We've been surprised how
little support there is for building mono-repo style mac + docker together
so this is a great start.

**Comment by viktorbenei** [comment]
> My understanding from the below references is that it is indeed "official"

I think you're right, but docker toolbox is no longer under active development (as far as I know). Should be still usable though (but for how long, that's still a question - e.g. it's no longer listed anywhere if you follow the "get docker" / install links from https://www.docker.com - for mac only the Docker for Mac app is listed through these install/getting started docs)

> We'll try that! Looks like it only adds about ~3min to the build time.
> Thanks so much, your responsiveness is amazing!

Any time and please keep us updated!

I think the discuss.bitrise.io thread should be the best place for the discussion, for visibility (in case others want to share their tips / related experience). We're definitely not against having Docker preinstalled on the Mac stacks, we just want to find a solution which is supported long term to reduce maintenance time on our side (in the past we had a couple of packages breaking frequently.. which makes the whole virtual machine/stack updating / provisioning incredibly hard :/ )

**Pull request merged**
