### PR TITLE
Pre-installing Carthage

### PR DESCRIPTION
**Pull request by kylejm**
Carthage is becoming increasingly popular. One of it's nicest features is that developers can attach pre-built archives of their frameworks to their releases so that CIs can run without having to build each dependancy.

Pre-installing Carthage on the Bitrise Mac OS X image would take another 1-2 mins off each build time, which would be great!

http://bitrise.uservoice.com/forums/235233-general/suggestions/11608896-pre-install-carthage

### CODE REVIEW

**Comment by viktorbenei** [comment]
Please also add a version print to the `system_report.sh`, as described in https://github.com/bitrise-io/osx-box-bootstrap#request-a-tool-to-be-pre-installed

**Comment by kylejm** [comment]
Hmm, what's failing @viktorbenei? 🤔

**Comment by viktorbenei** [comment]
Sorry, we just connected the PR check @kylejm - it only runs the `system_report.sh` but not the install, so it fails when it tries to check the Carthage version, because that's not yet pre-installed. We'll try to find a solution for this.

**Comment by kylejm** [comment]
Okay, no worries :blush:

**Comment by viktorbenei** [comment]
Will be available in the new VMs, starting with the Xcode 7.3 beta 2 VM which is under provision right now 😉

**Comment by kylejm** [comment]
\o/

**Pull request merged**
