### PR TITLE
Upgrade Flutter SDK to 1.20.3

### PR DESCRIPTION
**Pull request by yumatan**
We would like to upgrade Flutter SDK to the latest stable version.

- [Flutter SDK releases](https://flutter.dev/docs/development/tools/sdk/releases)
- [Changelog 1.20.3](https://github.com/flutter/flutter/releases/tag/1.20.3)

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [x] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [x] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

### CODE REVIEW

**Comment by fehersanyi-bitrise** [comment]
Hello @yumatan 
first of all, thank you for your PR!
I know it is not part of the PR template, but could you please update the related "test" case as well?
https://github.com/yumatan/osx-box-bootstrap/blob/b3d2218fe2f11fd4e2b36d76eef8eb8e4a6d9d89/roles/flutter/tests/test_flutter.py#L2

**Review by lmesz-bitrise — APPROVED** [review]

**Review by peterheja-bitrise — APPROVED** [review]
LGTM

**Comment by peterheja-bitrise** [comment]
@yumatan I'm going to close this PR.
Here is a version, where tests are fixed - but still has your contribution!
https://github.com/bitrise-io/osx-box-bootstrap/pull/310

Thank you, again, for your contribution! :)

**Comment by yumatan** [comment]
@fehersanyi-bitrise @peterheja-bitrise 
I am terribly sorry for the late response.
Thank you for reviewing my PR.

I will upgrade the related test case the next time I make the PRs.

**Comment by fehersanyi-bitrise** [comment]
@yumatan no problem, since that we did the PR ourselves :) 
https://github.com/bitrise-io/osx-box-bootstrap/pull/310

**Pull request closed without merging**
