### PR TITLE
[IN-2467] homebrew cask reverts

### PR DESCRIPTION
**Pull request by peterheja-bitrise**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I updated the corresponding tests if there were any.
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

### CODE REVIEW

**Review by bitrise-tom — APPROVED** [review]
:(

**Review by fehersanyi-bitrise — APPROVED** [review]
I would keep the "is it installed tho" check for the present state is not working :(

**Comment by bitrise-tom** [comment]
> I would keep the "is it installed tho" check for the present state is not working :(

This is a fair point, I would like to test this in Gen2 as there was a reason I made the changes to use `install_option` in the first place

**Comment by peterheja-bitrise** [comment]
> > I would keep the "is it installed tho" check for the present state is not working :(
> 
> This is a fair point, I would like to test this in Gen2 as there was a reason I made the changes to use `install_option` in the first place

Yes, but `install_option` is the abused `homebrew` version, where it is an INSTALL option, so it is not propagating to the parts, where it checks if it is installed.
Otherwise, it should be completely fine.

**Comment by bitrise-tom** [comment]
> , it should be completely fine.

I will test rather than assume

**Review by bitrise-tom — APPROVED** [review]

**Pull request merged**
