### PR TITLE
IN-1789 add simulators install

### PR DESCRIPTION
**Pull request by lmesz-bitrise**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

### CODE REVIEW

**Review by MrBlaise — APPROVED** [review]

**Review by fehersanyi-bitrise — COMMENTED** [review]
🧐 I mean, we should install TvOS and WatchOS stuff as well, don't we?

**Comment by lmesz-bitrise** [comment]
> 🧐 I mean, we should install TvOS and WatchOS stuff as well, don't we?

I hate when you are right, but again, you are right :D

**Review by peterheja-bitrise — CHANGES_REQUESTED** [review]
Installing two major's every minor version fills up our box.
Let's install only the latest major's minor versions - as it is currently done on 11.6 and 11.7 stable stacks.
Also, we should include iOS 13.6, because it is available on 11.7 and 12.0.x latest beta.

Otherwise, I really love this :)

**Review by MrBlaise — DISMISSED** [review]

**Review by peterheja-bitrise — CHANGES_REQUESTED** [review]
The max. top 3 of the latest major for:

 - iOS: 13.6 (with newer catalina), 13.5, 13.4, 13.3 (for older catalina)
 - watchOS: 6.1.1, 6.0
 - tvOS: 13.3, 13.2, 13.0

I think we should write in the newer Catalina version, as we generate new images with newer Catalina versions, like the 11.7, where 13.6 is available, and we should also upgrade the OS on 12.0.x beta stacks as well, so we can provide 13.6.

**Comment by lmesz-bitrise** [comment]
> The max. top 3 of the latest major for:
> 
> * iOS: 13.6 (with newer catalina), 13.5, 13.4, 13.3 (for older catalina)
> * watchOS: 6.1.1, 6.0
> * tvOS: 13.3, 13.2, 13.0
> 
> I think we should write in the newer Catalina version, as we generate new images with newer Catalina versions, like the 11.7, where 13.6 is available, and we should also upgrade the OS on 12.0.x beta stacks as well, so we can provide 13.6.

I'll add 13.6, but keep in mind that the install-xcode role will install 11.7 stack, not 12.

**Review by MrBlaise — APPROVED** [review]

**Review by bitrise-tom — APPROVED** [review]

**Review by peterheja-bitrise — APPROVED** [review]
lgtm

**Pull request merged**
