### PR TITLE
Add support for swift-sh

### PR DESCRIPTION
**Pull request by mackoj**
Adding a tool that simplifies a lot the use of swift as a scripting language

- https://github.com/mxcl/swift-sh
- https://nshipster.com/swift-sh/

Update LTS and weekly images

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [x] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [x] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [x] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

### CODE REVIEW

**Comment by fehersanyi-bitrise** [comment]
LGTM

**Comment by mackoj** [comment]
@fehersanyi-bitrise I'm not sure about the to this file `roles/weekly-update-shared/tasks/main.yml`

**Comment by ghaabor** [comment]
@mackoj please use the same syntax in weekly-update-shared as in the other one.
You can either do 
```
- name: brew install mxcl/made/swift-sh
  homebrew: name=swift-sh state=present
```
which won't install the latest version every week, or
```
- name: brew install mxcl/made/swift-sh
  homebrew: name=swift-sh state=latest
```
which will actually update the tool every week when we do the weekly VM updates, I'll leave this decision to you.

**Comment by mackoj** [comment]
Thanks @ghaabor and @fehersanyi-bitrise for the review.

**Pull request merged**
