### PR TITLE
Pre-installing jazzy

### PR DESCRIPTION
**Pull request by Dinsen**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [✓] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added

### CODE REVIEW

**Comment by viktorbenei** [comment]
Are you sure that this is the name of the brew formula?

```
$ brew install jazzy
Error: No available formula with the name "jazzy"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

**Comment by Dinsen** [comment]
Damn, it's not available through brew. Only with gem.
I'm not sure how to add it with gem in playbook.yml?

**Comment by viktorbenei** [comment]
https://github.com/bitrise-io/osx-box-bootstrap/blob/master/playbook.yml#L178

we just added one more PR checkpoint, related to whether the tool requires frequent update, please consider that one too: https://github.com/bitrise-io/osx-box-bootstrap/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by viktorbenei** [comment]
Another note, just tested the install of jazzy - with the `--no-document` flag the gem takes ~19 seconds to install; I'm not sure whether it should be preinstalled, as you most likely want a specific version of the gem anyway, in which case a preinstalled version won't help much

**Pull request closed without merging**
