### PR TITLE
Version updates:

### PR DESCRIPTION
**Pull request by koral--**
Flutter 2.2.3
Android commandline tools 7302050
Android NDK 21e
Android build tools 30.0.1 - 30.0.3

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [x] I updated the corresponding tests if there were any.
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [x] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [x] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

### CODE REVIEW

**Review by fehersanyi-bitrise — DISMISSED** [review]
lgtm

**Comment by koral--** [comment]
@fehersanyi-bitrise could you paste CI build error message?

**Comment by peterheja-bitrise** [comment]
> @fehersanyi-bitrise could you paste CI build error message?

We fail our CI hard on external contributions currently.

**Comment by fehersanyi-bitrise** [comment]
hey @koral-- as @peterheja-bitrise said, we have some custom logic in the CI that fails on outside contributor PRs, but I ran the tests for these roles locally, and everything seems to work fine. So I believe we will be able to add these tools to the configuration

**Review by bitrise-tom — APPROVED** [review]

**Comment by bitrise-tom** [comment]
Hi Koral, 

Can you please fix up the merge conflicts here and I will merge it all in for release next week.

Thanks

**Comment by koral--** [comment]
Done

**Pull request merged**
