### PR TITLE
jce-unlimited-strength-policy preinstalled cask added

### PR DESCRIPTION
**Pull request by koral--**
Allows connectivity using strong cryptography.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [x] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added

### CODE REVIEW

**Comment by viktorbenei** [comment]
What does this tool do exactly? And how much time does it take to `brew install` it @koral-- ?

**Comment by koral--** [comment]
Here is the official website: http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html
This is not a tool but rather JDK configuration files. By default max allowed key length is 128 on Oracle JDK, after installing JCE it becomes unlimited.
With 128 you can not connect to HTTP servers with modern configuration e.g. using `AES256+EDH` SSL cipher.
Reinstallation takes about 1s on my macBook:
```
$ time brew cask reinstall jce-unlimited-strength-policy
==> Caveats
Installing this Cask means you have AGREED to the Oracle Binary Code License Agreement for Java SE at
  https://www.oracle.com/technetwork/java/javase/terms/license/index.html

jce-unlimited-strength-policy will be uninstalled when the Java Cask is uninstalled or reinstalled

==> Satisfying dependencies
==> Downloading http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
Already downloaded: /Users/koral/Library/Caches/Homebrew/Cask/jce-unlimited-strength-policy--1.8.zip
==> Verifying checksum for Cask jce-unlimited-strength-policy
==> Uninstalling Cask jce-unlimited-strength-policy
==> Installing Cask jce-unlimited-strength-policy
🍺  jce-unlimited-strength-policy was successfully installed!

real	0m1.140s
user	0m0.625s
sys	0m0.345s
```
PS. JDK on Linux stack (at least non-LTS) already includes JCE.

**Comment by viktorbenei** [comment]
Thanks @koral-- , I'll check it ASAP a bit more. Sorry, I was on holiday and still catching up, so it won't be accepted in this week's updates, but I'll definitely check it before the next update!

**Comment by koral--** [comment]
OK, understand.

**Comment by viktorbenei** [comment]
Thanks :)

**Comment by ghaabor** [comment]
Hey @koral--, thanks for the PR! We've reviewed it and we're going to pull it in. It's going to be included in the Xcode Edge stack rolling out the next weekend (Sept 16) and all new MacOS stacks created afterwards.

**Comment by viktorbenei** [comment]
Actually @koral-- we found an issue with the PR, the system report:

```
brew cask info jce-unlimited-strength-policy
```

this prints **the version available in brew**, not the installed version. E.g. I never installed this cask on my Mac and I get:

```
$ brew cask info jce-unlimited-strength-policy

jce-unlimited-strength-policy: 1.8
https://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html
Not installed
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/jce-unlimited-strength-policy.rb
==> Name
Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files
==> Artifacts
==> Caveats
Installing this Cask means you have AGREED to the Oracle Binary Code License Agreement for Java SE at
  https://www.oracle.com/technetwork/java/javase/terms/license/index.html

jce-unlimited-strength-policy will be uninstalled when the Java Cask is uninstalled or reinstalled
```

Do you have a suggestion how else we could print the version of `jce-unlimited-strength-policy`?

**Comment by koral--** [comment]
`brew cask list jce-unlimited-strength-policy &&  brew cask info jce-unlimited-strength-policy`

Here is the output (cask is installed initially):
```
$ brew cask list jce-unlimited-strength-policy &&  brew cask info jce-unlimited-strength-policy
jce-unlimited-strength-policy: 1.8
https://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html
/usr/local/Caskroom/jce-unlimited-strength-policy/1.8 (3 files, 13.3KB)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/jce-unlimited-strength-policy.rb
==> Name
Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files
==> Artifacts
==> Caveats
Installing this Cask means you have AGREED to the Oracle Binary Code License Agreement for Java SE at
  https://www.oracle.com/technetwork/java/javase/terms/license/index.html

jce-unlimited-strength-policy will be uninstalled when the Java Cask is uninstalled or reinstalled

$ brew cask uninstall jce-unlimited-strength-policy
==> Uninstalling Cask jce-unlimited-strength-policy
$ brew cask list jce-unlimited-strength-policy &&  brew cask info jce-unlimited-strength-policy
Error: Cask 'jce-unlimited-strength-policy' is not installed.
Error: Listing incomplete.
```

Should I create new PR with that?

**Comment by viktorbenei** [comment]
> brew cask list jce-unlimited-strength-policy

That's a neat trick, didn't know about it ;)

> Should I create new PR with that?

We'll figure something out, worst case we'll simply not include it in the system report, or just include the output of `brew cask list`..

P.S.: it seems `jce-unlimited-strength-policy` is not versioned, its version is actually the java version it can be installed for, not `jce-unlimited-strength-policy` or the cask's own version

**Comment by koral--** [comment]
> so maybe a simple "installed / not installed" is enough

Currently, there is no other possibility since 1.8 is the only version available in caskroom. So it seems to be fine for the purpose of system report.

Cask has a version number: https://github.com/caskroom/homebrew-cask/blob/master/Casks/jce-unlimited-strength-policy.rb#L2

JCE itself is versioned, versions are the same as java major version number:
http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html
http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

In java 9 such thing as JCE won't be probably ever needed.

**Comment by viktorbenei** [comment]
No worries, we ended up printing just "installed" / "not installed" : https://github.com/bitrise-io/osx-box-bootstrap/pull/51/files

**Comment by koral--** [comment]
🆒  it can be done even simpler: https://github.com/bitrise-io/osx-box-bootstrap/pull/51/files#r137609853 ;)

**Comment by viktorbenei** [comment]
@koral-- you're absolutely right, thanks! ;)

**Comment by koral--** [comment]
FYI `java` cask has been updated to 9 and `jce-unlimited-strength-policy` cask is being moved to caskroom/versions tap: https://github.com/caskroom/homebrew-cask/issues/38574
It seems that playbook needs to be updated.

**Comment by viktorbenei** [comment]
Thanks @koral-- for the heads up! Can you please create a separate issue, for tracking purposes?

**Pull request merged**
